upstream fastcgi_backend {
    server php:9000;
}

server {
    listen 8080;
    server_name localhost;
    set $MAGE_ROOT /var/www/html;

    root  $MAGE_ROOT/pub;
    index index.php;
    autoindex off;
    charset UTF-8;
    error_page 404 403 = /errors/404.php;

    client_max_body_size 64m;

    location ~ /\.                { deny all; }
    location ~ ^/app/             { deny all; }
    location ~ ^/bin/             { deny all; }
    location ~ ^/dev/             { deny all; }
    location ~ ^/lib/             { deny all; }
    location ~ ^/vendor/          { deny all; }
    location ~ ^/var/             { deny all; }
    location ~ ^/generated/       { deny all; }

    location ~* ^/setup($|/) {
        root $MAGE_ROOT;
        location ~ ^/setup/index\.php {
            fastcgi_pass   fastcgi_backend;
            fastcgi_param  PHP_VALUE "memory_limit=756M \n max_execution_time=600";
            fastcgi_read_timeout 600s;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }
        location ~ ^/setup/(?!pub/). { deny all; }
    }

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location /static/ {
        location ~ ^/static/version\d*/ {
            rewrite ^/static/version\d*/(.+)$ /static/$1 last;
        }
        if (!-f $request_filename) {
            rewrite ^/static/?(.*)$ /static.php?resource=$1 last;
        }
    }

    location /media/ {
        location ~ ^/media/(downloadable|customer|import|custom_options)/ { deny all; }
        try_files $uri $uri/ /get.php$is_args$args;
    }

    location /errors/ { try_files $uri =404; }

    location ~ ^/(index|get|static|errors/report|errors/404|errors/503|health_check)\.php$ {
        try_files $uri =404;
        fastcgi_pass   fastcgi_backend;
        fastcgi_param  PHP_VALUE "memory_limit=756M \n max_execution_time=600";
        fastcgi_read_timeout 600s;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~* \.php$ { deny all; }

    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
}
